# Generated by Django 5.2.7 on 2025-12-13 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_recreate_tables_with_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
