# Generated by Django 5.2.7 on 2025-12-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_comment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
