# Generated by Django 5.2.7 on 2025-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_alter_comment_content_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_raw',
            field=models.TextField(default=''),
        ),
    ]
