# Generated by Django 5.2.7 on 2025-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_post_content_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_raw',
            field=models.TextField(default=''),
        ),
    ]
