# Generated by Django 5.2.7 on 2025-12-11 15:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.bg_upload_path),
        ),
    ]
