# Generated by Django 5.2.7 on 2025-12-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='这个用户很懒，还没有设置个人简介。', max_length=500),
        ),
    ]
